38 user verification request
Mateusz-Dobrzynski/meals-management-system pull request #11
Opened 2023-08-23 10:40 UTC by Mateusz-Dobrzynski

This PR is not ready yet, as not all tests pass 🔴
Verification request included in this PR will be sent by email to verify an account. This is yet to be implemented.

2023-08-31 12:56 UTC, hubertborysowski requested changes
1 Warning found. Potential magic values has been found as well.

2023-08-31 12:56 UTC, hubertborysowski commented on src/test/java/org/lookout_studios/meals_management_system/meals_management_system/RegistrationServiceTests.java
Line 19: Warning `import com.github.tomakehurst.wiremock.junit5.WireMockRuntimeInfo;` is never used.

2023-08-31 12:56 UTC, hubertborysowski commented on src/main/java/org/lookout_studios/meals_management_system/meals_management_system/VerificationService.java
> +    @ApiResponse(responseCode = "500", description = "${api.response-codes.internalServerError.desc}", content = @Content)
Shouldn't the description fields be made in the same way as in previous lines - by using Strings?

2023-08-31 12:58 UTC, hubertborysowski commented
By the way, should we consider MySQL queries as magic values when not declared as strings? I probably should've asked that question earlier but it just came to my head now.

2023-09-01 08:59 UTC, Mateusz-Dobrzynski commented
Well, this would be the case but the content of the query always depends on the data that is requested. That's why queries are formatted with `String.format()`. While this is not the most elegant solution, it's the best one I could think of. We can always refactor it, should we come up with something better.

2023-09-01 09:41 UTC, Mateusz-Dobrzynski commented on src/main/java/org/lookout_studios/meals_management_system/meals_management_system/VerificationService.java
> +    @ApiResponse(responseCode = "500", description = "${api.response-codes.internalServerError.desc}", content = @Content)
Here I referenced templates present in `application.properties` to ensure consistency among different requests. Other than that, it's easier to change one property in a single file than to change variables in multiple files, if we decide to change it at some point. In other words, this makes code future-proof.

2023-09-01 11:03 UTC, hubertborysowski approved these changes
Everything works fine, code is understandable, clean and documented.

2023-09-01 12:00 UTC, merged